export const USER_LOGIN_INICIADO = 'USER_LOGIN_INICIADO';
export const USER_LOGIN_EXITO = 'USER_LOGIN_EXITO';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_INICIADO = 'USER_LOGOUT_INICIADO';
export const USER_LOGOUT_EXITO = 'USER_LOGOUT_EXITO';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';
